name: social_media_feed
description: "Social Feed"

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0 # Networking
  retrofit: ^4.0.1 # For generating API client
  json_annotation: ^4.9.0 # For parsing JSON
  freezed_annotation: ^2.4.4 # For code generation
  flutter_bloc: ^8.1.6 # State management with bloc & cubit
  equatable: ^2.0.5 # For value equality in entities and state
  dartz: ^0.10.1 # Error handling
  get_it: ^8.0.0 # Service locator
  hive_flutter: ^1.1.0 # Local storage
  timeago: ^3.7.0 # For date time


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^9.1.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
